// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5QbACu0-5iMB1pfXsU0zq7WTo7S7VlAo',
    appId: '1:71753084250:web:919f24af9e19a83620d763',
    messagingSenderId: '71753084250',
    projectId: 'yaar-motors',
    authDomain: 'yaar-motors.firebaseapp.com',
    storageBucket: 'yaar-motors.firebasestorage.app',
    measurementId: 'G-HDGT9D0Q73',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBFTNs5GgVjfL2_tsgY2ENlC7uDLRAey_Y',
    appId: '1:71753084250:android:9ec6fece39453a8720d763',
    messagingSenderId: '71753084250',
    projectId: 'yaar-motors',
    storageBucket: 'yaar-motors.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3A0yd4qw9Br3wV7yi0sPploMfAErAcjo',
    appId: '1:71753084250:ios:61a5fca5f3c0da7120d763',
    messagingSenderId: '71753084250',
    projectId: 'yaar-motors',
    storageBucket: 'yaar-motors.firebasestorage.app',
    iosBundleId: 'com.mycompany.CounterApp',
  );
}
